// Code generated by d3. DO NOT EDIT.

package relation

import "fmt"
import "d3/orm/entity"

func (f *fwTestEntity1) D3Token() entity.MetaToken {
	return entity.MetaToken{
		Tpl:       (*fwTestEntity1)(nil),
		TableName: "",
		Tools: entity.InternalTools{
			FieldExtractor: f.__d3_createFieldExtractor(),
		},
	}
}

func (f *fwTestEntity1) __d3_createFieldExtractor() entity.FieldExtractor {
	return func(s interface{}, name string) (interface{}, error) {
		sTyped, ok := s.(*fwTestEntity1)
		if !ok {
			return nil, fmt.Errorf("invalid entity type")
		}

		switch name {

		case "Id":
			return sTyped.Id, nil

		case "Rel":
			return sTyped.Rel, nil

		case "Data":
			return sTyped.Data, nil

		default:
			return nil, fmt.Errorf("field %s not found", name)
		}
	}
}

func (f *fwTestEntity2) D3Token() entity.MetaToken {
	return entity.MetaToken{
		Tpl:       (*fwTestEntity2)(nil),
		TableName: "",
		Tools: entity.InternalTools{
			FieldExtractor: f.__d3_createFieldExtractor(),
		},
	}
}

func (f *fwTestEntity2) __d3_createFieldExtractor() entity.FieldExtractor {
	return func(s interface{}, name string) (interface{}, error) {
		sTyped, ok := s.(*fwTestEntity2)
		if !ok {
			return nil, fmt.Errorf("invalid entity type")
		}

		switch name {

		case "Id":
			return sTyped.Id, nil

		case "Rel":
			return sTyped.Rel, nil

		case "Data":
			return sTyped.Data, nil

		default:
			return nil, fmt.Errorf("field %s not found", name)
		}
	}
}

func (f *fwTestEntity3) D3Token() entity.MetaToken {
	return entity.MetaToken{
		Tpl:       (*fwTestEntity3)(nil),
		TableName: "",
		Tools: entity.InternalTools{
			FieldExtractor: f.__d3_createFieldExtractor(),
		},
	}
}

func (f *fwTestEntity3) __d3_createFieldExtractor() entity.FieldExtractor {
	return func(s interface{}, name string) (interface{}, error) {
		sTyped, ok := s.(*fwTestEntity3)
		if !ok {
			return nil, fmt.Errorf("invalid entity type")
		}

		switch name {

		case "Id":
			return sTyped.Id, nil

		case "Rel":
			return sTyped.Rel, nil

		case "Data":
			return sTyped.Data, nil

		default:
			return nil, fmt.Errorf("field %s not found", name)
		}
	}
}

func (f *fwTestEntity4) D3Token() entity.MetaToken {
	return entity.MetaToken{
		Tpl:       (*fwTestEntity4)(nil),
		TableName: "",
		Tools: entity.InternalTools{
			FieldExtractor: f.__d3_createFieldExtractor(),
		},
	}
}

func (f *fwTestEntity4) __d3_createFieldExtractor() entity.FieldExtractor {
	return func(s interface{}, name string) (interface{}, error) {
		sTyped, ok := s.(*fwTestEntity4)
		if !ok {
			return nil, fmt.Errorf("invalid entity type")
		}

		switch name {

		case "Id":
			return sTyped.Id, nil

		case "Data":
			return sTyped.Data, nil

		default:
			return nil, fmt.Errorf("field %s not found", name)
		}
	}
}
