// Code generated by d3. DO NOT EDIT.

package cache

import "fmt"
import "d3/orm/entity"

func (e *entity1) D3Token() entity.MetaToken {
	return entity.MetaToken{
		Tpl:       (*entity1)(nil),
		TableName: "",
		Tools: entity.InternalTools{
			FieldExtractor: e.__d3_createFieldExtractor(),
		},
	}
}

func (e *entity1) __d3_createFieldExtractor() entity.FieldExtractor {
	return func(s interface{}, name string) (interface{}, error) {
		sTyped, ok := s.(*entity1)
		if !ok {
			return nil, fmt.Errorf("invalid entity type")
		}

		switch name {

		case "Id":
			return sTyped.Id, nil

		case "Rel":
			return sTyped.Rel, nil

		case "Data":
			return sTyped.Data, nil

		default:
			return nil, fmt.Errorf("field %s not found", name)
		}
	}
}

func (e *entity2) D3Token() entity.MetaToken {
	return entity.MetaToken{
		Tpl:       (*entity2)(nil),
		TableName: "",
		Tools: entity.InternalTools{
			FieldExtractor: e.__d3_createFieldExtractor(),
		},
	}
}

func (e *entity2) __d3_createFieldExtractor() entity.FieldExtractor {
	return func(s interface{}, name string) (interface{}, error) {
		sTyped, ok := s.(*entity2)
		if !ok {
			return nil, fmt.Errorf("invalid entity type")
		}

		switch name {

		case "Id":
			return sTyped.Id, nil

		case "Data":
			return sTyped.Data, nil

		default:
			return nil, fmt.Errorf("field %s not found", name)
		}
	}
}
