name: "coverage"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cover:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: d3db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14.x

      - name: Calc coverage
        run: |
          go test -coverpkg=./... ./... -count=1 -coverprofile=cover.cov.tmp -v
          cat cover.cov.tmp | grep -v "_d3.go" > profile.cov
        env:
          D3_PG_TEST_DB: "postgres://postgres:postgres@0.0.0.0:5432/d3db"

      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          GO111MODULE=off go get github.com/mattn/goveralls
          $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github